#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmecyMgt
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pharmecy Mgt.")]
	public partial class PharmecyMgtDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_current_drug(tbl_current_drug instance);
    partial void Updatetbl_current_drug(tbl_current_drug instance);
    partial void Deletetbl_current_drug(tbl_current_drug instance);
    partial void Inserttbl_login(tbl_login instance);
    partial void Updatetbl_login(tbl_login instance);
    partial void Deletetbl_login(tbl_login instance);
    partial void Inserttbl_order(tbl_order instance);
    partial void Updatetbl_order(tbl_order instance);
    partial void Deletetbl_order(tbl_order instance);
    partial void Inserttbl_product(tbl_product instance);
    partial void Updatetbl_product(tbl_product instance);
    partial void Deletetbl_product(tbl_product instance);
    partial void Inserttbl_return(tbl_return instance);
    partial void Updatetbl_return(tbl_return instance);
    partial void Deletetbl_return(tbl_return instance);
    partial void Inserttbl_sell(tbl_sell instance);
    partial void Updatetbl_sell(tbl_sell instance);
    partial void Deletetbl_sell(tbl_sell instance);
    partial void Inserttbl_staffinfo(tbl_staffinfo instance);
    partial void Updatetbl_staffinfo(tbl_staffinfo instance);
    partial void Deletetbl_staffinfo(tbl_staffinfo instance);
    partial void Inserttbl_withdrawl(tbl_withdrawl instance);
    partial void Updatetbl_withdrawl(tbl_withdrawl instance);
    partial void Deletetbl_withdrawl(tbl_withdrawl instance);
    #endregion
		
		public PharmecyMgtDataContext() : 
				base(global::PharmecyMgt.Properties.Settings.Default.Pharmecy_Mgt_ConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public PharmecyMgtDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PharmecyMgtDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PharmecyMgtDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PharmecyMgtDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_current_drug> tbl_current_drugs
		{
			get
			{
				return this.GetTable<tbl_current_drug>();
			}
		}
		
		public System.Data.Linq.Table<tbl_login> tbl_logins
		{
			get
			{
				return this.GetTable<tbl_login>();
			}
		}
		
		public System.Data.Linq.Table<tbl_order> tbl_orders
		{
			get
			{
				return this.GetTable<tbl_order>();
			}
		}
		
		public System.Data.Linq.Table<tbl_product> tbl_products
		{
			get
			{
				return this.GetTable<tbl_product>();
			}
		}
		
		public System.Data.Linq.Table<tbl_return> tbl_returns
		{
			get
			{
				return this.GetTable<tbl_return>();
			}
		}
		
		public System.Data.Linq.Table<tbl_sell> tbl_sells
		{
			get
			{
				return this.GetTable<tbl_sell>();
			}
		}
		
		public System.Data.Linq.Table<tbl_staffinfo> tbl_staffinfos
		{
			get
			{
				return this.GetTable<tbl_staffinfo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_withdrawl> tbl_withdrawls
		{
			get
			{
				return this.GetTable<tbl_withdrawl>();
			}
		}
		
		public System.Data.Linq.Table<View_order_product> View_order_products
		{
			get
			{
				return this.GetTable<View_order_product>();
			}
		}
		
		public System.Data.Linq.Table<view_sell> view_sells
		{
			get
			{
				return this.GetTable<view_sell>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_current_drugs")]
	public partial class tbl_current_drug : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _drug_sn;
		
		private int _product_sn;
		
		private double _quantity;
		
		private EntityRef<tbl_product> _tbl_product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondrug_snChanging(int value);
    partial void Ondrug_snChanged();
    partial void Onproduct_snChanging(int value);
    partial void Onproduct_snChanged();
    partial void OnquantityChanging(double value);
    partial void OnquantityChanged();
    #endregion
		
		public tbl_current_drug()
		{
			this._tbl_product = default(EntityRef<tbl_product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drug_sn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int drug_sn
		{
			get
			{
				return this._drug_sn;
			}
			set
			{
				if ((this._drug_sn != value))
				{
					this.Ondrug_snChanging(value);
					this.SendPropertyChanging();
					this._drug_sn = value;
					this.SendPropertyChanged("drug_sn");
					this.Ondrug_snChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sn", DbType="Int NOT NULL")]
		public int product_sn
		{
			get
			{
				return this._product_sn;
			}
			set
			{
				if ((this._product_sn != value))
				{
					if (this._tbl_product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_snChanging(value);
					this.SendPropertyChanging();
					this._product_sn = value;
					this.SendPropertyChanged("product_sn");
					this.Onproduct_snChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Float NOT NULL")]
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_product_tbl_current_drug", Storage="_tbl_product", ThisKey="product_sn", OtherKey="product_sn", IsForeignKey=true)]
		public tbl_product tbl_product
		{
			get
			{
				return this._tbl_product.Entity;
			}
			set
			{
				tbl_product previousValue = this._tbl_product.Entity;
				if (((previousValue != value) 
							|| (this._tbl_product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_product.Entity = null;
						previousValue.tbl_current_drugs.Remove(this);
					}
					this._tbl_product.Entity = value;
					if ((value != null))
					{
						value.tbl_current_drugs.Add(this);
						this._product_sn = value.product_sn;
					}
					else
					{
						this._product_sn = default(int);
					}
					this.SendPropertyChanged("tbl_product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_login")]
	public partial class tbl_login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _login_sn;
		
		private string _User_Id;
		
		private string _User_Type;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlogin_snChanging(int value);
    partial void Onlogin_snChanged();
    partial void OnUser_IdChanging(string value);
    partial void OnUser_IdChanged();
    partial void OnUser_TypeChanging(string value);
    partial void OnUser_TypeChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public tbl_login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_sn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int login_sn
		{
			get
			{
				return this._login_sn;
			}
			set
			{
				if ((this._login_sn != value))
				{
					this.Onlogin_snChanging(value);
					this.SendPropertyChanging();
					this._login_sn = value;
					this.SendPropertyChanged("login_sn");
					this.Onlogin_snChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string User_Type
		{
			get
			{
				return this._User_Type;
			}
			set
			{
				if ((this._User_Type != value))
				{
					this.OnUser_TypeChanging(value);
					this.SendPropertyChanging();
					this._User_Type = value;
					this.SendPropertyChanged("User_Type");
					this.OnUser_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_order")]
	public partial class tbl_order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _order_id;
		
		private int _product_sn;
		
		private int _unq_orderid;
		
		private string _order_type;
		
		private double _quantity;
		
		private double _bonus_product;
		
		private string _payment_type;
		
		private double _price;
		
		private double _paid_amount;
		
		private double _due_amount;
		
		private string _ordered_to;
		
		private int _contact_no;
		
		private string _order_status;
		
		private System.DateTime _date_time;
		
		private EntityRef<tbl_product> _tbl_product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void Onproduct_snChanging(int value);
    partial void Onproduct_snChanged();
    partial void Onunq_orderidChanging(int value);
    partial void Onunq_orderidChanged();
    partial void Onorder_typeChanging(string value);
    partial void Onorder_typeChanged();
    partial void OnquantityChanging(double value);
    partial void OnquantityChanged();
    partial void Onbonus_productChanging(double value);
    partial void Onbonus_productChanged();
    partial void Onpayment_typeChanging(string value);
    partial void Onpayment_typeChanged();
    partial void OnpriceChanging(double value);
    partial void OnpriceChanged();
    partial void Onpaid_amountChanging(double value);
    partial void Onpaid_amountChanged();
    partial void Ondue_amountChanging(double value);
    partial void Ondue_amountChanged();
    partial void Onordered_toChanging(string value);
    partial void Onordered_toChanged();
    partial void Oncontact_noChanging(int value);
    partial void Oncontact_noChanged();
    partial void Onorder_statusChanging(string value);
    partial void Onorder_statusChanged();
    partial void Ondate_timeChanging(System.DateTime value);
    partial void Ondate_timeChanged();
    #endregion
		
		public tbl_order()
		{
			this._tbl_product = default(EntityRef<tbl_product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sn", DbType="Int NOT NULL")]
		public int product_sn
		{
			get
			{
				return this._product_sn;
			}
			set
			{
				if ((this._product_sn != value))
				{
					if (this._tbl_product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_snChanging(value);
					this.SendPropertyChanging();
					this._product_sn = value;
					this.SendPropertyChanged("product_sn");
					this.Onproduct_snChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unq_orderid", DbType="Int NOT NULL")]
		public int unq_orderid
		{
			get
			{
				return this._unq_orderid;
			}
			set
			{
				if ((this._unq_orderid != value))
				{
					this.Onunq_orderidChanging(value);
					this.SendPropertyChanging();
					this._unq_orderid = value;
					this.SendPropertyChanged("unq_orderid");
					this.Onunq_orderidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string order_type
		{
			get
			{
				return this._order_type;
			}
			set
			{
				if ((this._order_type != value))
				{
					this.Onorder_typeChanging(value);
					this.SendPropertyChanging();
					this._order_type = value;
					this.SendPropertyChanged("order_type");
					this.Onorder_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Float NOT NULL")]
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bonus_product", DbType="Float NOT NULL")]
		public double bonus_product
		{
			get
			{
				return this._bonus_product;
			}
			set
			{
				if ((this._bonus_product != value))
				{
					this.Onbonus_productChanging(value);
					this.SendPropertyChanging();
					this._bonus_product = value;
					this.SendPropertyChanged("bonus_product");
					this.Onbonus_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string payment_type
		{
			get
			{
				return this._payment_type;
			}
			set
			{
				if ((this._payment_type != value))
				{
					this.Onpayment_typeChanging(value);
					this.SendPropertyChanging();
					this._payment_type = value;
					this.SendPropertyChanged("payment_type");
					this.Onpayment_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid_amount", DbType="Float NOT NULL")]
		public double paid_amount
		{
			get
			{
				return this._paid_amount;
			}
			set
			{
				if ((this._paid_amount != value))
				{
					this.Onpaid_amountChanging(value);
					this.SendPropertyChanging();
					this._paid_amount = value;
					this.SendPropertyChanged("paid_amount");
					this.Onpaid_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_due_amount", DbType="Float NOT NULL")]
		public double due_amount
		{
			get
			{
				return this._due_amount;
			}
			set
			{
				if ((this._due_amount != value))
				{
					this.Ondue_amountChanging(value);
					this.SendPropertyChanging();
					this._due_amount = value;
					this.SendPropertyChanged("due_amount");
					this.Ondue_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordered_to", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ordered_to
		{
			get
			{
				return this._ordered_to;
			}
			set
			{
				if ((this._ordered_to != value))
				{
					this.Onordered_toChanging(value);
					this.SendPropertyChanging();
					this._ordered_to = value;
					this.SendPropertyChanged("ordered_to");
					this.Onordered_toChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="Int NOT NULL")]
		public int contact_no
		{
			get
			{
				return this._contact_no;
			}
			set
			{
				if ((this._contact_no != value))
				{
					this.Oncontact_noChanging(value);
					this.SendPropertyChanging();
					this._contact_no = value;
					this.SendPropertyChanged("contact_no");
					this.Oncontact_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string order_status
		{
			get
			{
				return this._order_status;
			}
			set
			{
				if ((this._order_status != value))
				{
					this.Onorder_statusChanging(value);
					this.SendPropertyChanging();
					this._order_status = value;
					this.SendPropertyChanged("order_status");
					this.Onorder_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime NOT NULL")]
		public System.DateTime date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this.Ondate_timeChanging(value);
					this.SendPropertyChanging();
					this._date_time = value;
					this.SendPropertyChanged("date_time");
					this.Ondate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_product_tbl_order", Storage="_tbl_product", ThisKey="product_sn", OtherKey="product_sn", IsForeignKey=true)]
		public tbl_product tbl_product
		{
			get
			{
				return this._tbl_product.Entity;
			}
			set
			{
				tbl_product previousValue = this._tbl_product.Entity;
				if (((previousValue != value) 
							|| (this._tbl_product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_product.Entity = null;
						previousValue.tbl_orders.Remove(this);
					}
					this._tbl_product.Entity = value;
					if ((value != null))
					{
						value.tbl_orders.Add(this);
						this._product_sn = value.product_sn;
					}
					else
					{
						this._product_sn = default(int);
					}
					this.SendPropertyChanged("tbl_product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_product")]
	public partial class tbl_product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _product_sn;
		
		private string _product_name;
		
		private string _product_group;
		
		private double _quantity_per_box;
		
		private string _company_name;
		
		private double _price_per_box;
		
		private double _comission_rate_percentege;
		
		private EntitySet<tbl_current_drug> _tbl_current_drugs;
		
		private EntitySet<tbl_order> _tbl_orders;
		
		private EntitySet<tbl_return> _tbl_returns;
		
		private EntitySet<tbl_sell> _tbl_sells;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_snChanging(int value);
    partial void Onproduct_snChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onproduct_groupChanging(string value);
    partial void Onproduct_groupChanged();
    partial void Onquantity_per_boxChanging(double value);
    partial void Onquantity_per_boxChanged();
    partial void Oncompany_nameChanging(string value);
    partial void Oncompany_nameChanged();
    partial void Onprice_per_boxChanging(double value);
    partial void Onprice_per_boxChanged();
    partial void Oncomission_rate_percentegeChanging(double value);
    partial void Oncomission_rate_percentegeChanged();
    #endregion
		
		public tbl_product()
		{
			this._tbl_current_drugs = new EntitySet<tbl_current_drug>(new Action<tbl_current_drug>(this.attach_tbl_current_drugs), new Action<tbl_current_drug>(this.detach_tbl_current_drugs));
			this._tbl_orders = new EntitySet<tbl_order>(new Action<tbl_order>(this.attach_tbl_orders), new Action<tbl_order>(this.detach_tbl_orders));
			this._tbl_returns = new EntitySet<tbl_return>(new Action<tbl_return>(this.attach_tbl_returns), new Action<tbl_return>(this.detach_tbl_returns));
			this._tbl_sells = new EntitySet<tbl_sell>(new Action<tbl_sell>(this.attach_tbl_sells), new Action<tbl_sell>(this.detach_tbl_sells));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int product_sn
		{
			get
			{
				return this._product_sn;
			}
			set
			{
				if ((this._product_sn != value))
				{
					this.Onproduct_snChanging(value);
					this.SendPropertyChanging();
					this._product_sn = value;
					this.SendPropertyChanged("product_sn");
					this.Onproduct_snChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_group", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string product_group
		{
			get
			{
				return this._product_group;
			}
			set
			{
				if ((this._product_group != value))
				{
					this.Onproduct_groupChanging(value);
					this.SendPropertyChanging();
					this._product_group = value;
					this.SendPropertyChanged("product_group");
					this.Onproduct_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity_per_box", DbType="Float NOT NULL")]
		public double quantity_per_box
		{
			get
			{
				return this._quantity_per_box;
			}
			set
			{
				if ((this._quantity_per_box != value))
				{
					this.Onquantity_per_boxChanging(value);
					this.SendPropertyChanging();
					this._quantity_per_box = value;
					this.SendPropertyChanged("quantity_per_box");
					this.Onquantity_per_boxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string company_name
		{
			get
			{
				return this._company_name;
			}
			set
			{
				if ((this._company_name != value))
				{
					this.Oncompany_nameChanging(value);
					this.SendPropertyChanging();
					this._company_name = value;
					this.SendPropertyChanged("company_name");
					this.Oncompany_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_per_box", DbType="Float NOT NULL")]
		public double price_per_box
		{
			get
			{
				return this._price_per_box;
			}
			set
			{
				if ((this._price_per_box != value))
				{
					this.Onprice_per_boxChanging(value);
					this.SendPropertyChanging();
					this._price_per_box = value;
					this.SendPropertyChanged("price_per_box");
					this.Onprice_per_boxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comission_rate_percentege", DbType="Float NOT NULL")]
		public double comission_rate_percentege
		{
			get
			{
				return this._comission_rate_percentege;
			}
			set
			{
				if ((this._comission_rate_percentege != value))
				{
					this.Oncomission_rate_percentegeChanging(value);
					this.SendPropertyChanging();
					this._comission_rate_percentege = value;
					this.SendPropertyChanged("comission_rate_percentege");
					this.Oncomission_rate_percentegeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_product_tbl_current_drug", Storage="_tbl_current_drugs", ThisKey="product_sn", OtherKey="product_sn")]
		public EntitySet<tbl_current_drug> tbl_current_drugs
		{
			get
			{
				return this._tbl_current_drugs;
			}
			set
			{
				this._tbl_current_drugs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_product_tbl_order", Storage="_tbl_orders", ThisKey="product_sn", OtherKey="product_sn")]
		public EntitySet<tbl_order> tbl_orders
		{
			get
			{
				return this._tbl_orders;
			}
			set
			{
				this._tbl_orders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_product_tbl_return", Storage="_tbl_returns", ThisKey="product_sn", OtherKey="product_sn")]
		public EntitySet<tbl_return> tbl_returns
		{
			get
			{
				return this._tbl_returns;
			}
			set
			{
				this._tbl_returns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_product_tbl_sell", Storage="_tbl_sells", ThisKey="product_sn", OtherKey="product_sn")]
		public EntitySet<tbl_sell> tbl_sells
		{
			get
			{
				return this._tbl_sells;
			}
			set
			{
				this._tbl_sells.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_current_drugs(tbl_current_drug entity)
		{
			this.SendPropertyChanging();
			entity.tbl_product = this;
		}
		
		private void detach_tbl_current_drugs(tbl_current_drug entity)
		{
			this.SendPropertyChanging();
			entity.tbl_product = null;
		}
		
		private void attach_tbl_orders(tbl_order entity)
		{
			this.SendPropertyChanging();
			entity.tbl_product = this;
		}
		
		private void detach_tbl_orders(tbl_order entity)
		{
			this.SendPropertyChanging();
			entity.tbl_product = null;
		}
		
		private void attach_tbl_returns(tbl_return entity)
		{
			this.SendPropertyChanging();
			entity.tbl_product = this;
		}
		
		private void detach_tbl_returns(tbl_return entity)
		{
			this.SendPropertyChanging();
			entity.tbl_product = null;
		}
		
		private void attach_tbl_sells(tbl_sell entity)
		{
			this.SendPropertyChanging();
			entity.tbl_product = this;
		}
		
		private void detach_tbl_sells(tbl_sell entity)
		{
			this.SendPropertyChanging();
			entity.tbl_product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_return")]
	public partial class tbl_return : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _return_sn;
		
		private int _product_sn;
		
		private string _product_name;
		
		private double _quantity;
		
		private System.Nullable<double> _cutback_rate;
		
		private double _price;
		
		private System.DateTime _date_time;
		
		private EntityRef<tbl_product> _tbl_product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreturn_snChanging(int value);
    partial void Onreturn_snChanged();
    partial void Onproduct_snChanging(int value);
    partial void Onproduct_snChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void OnquantityChanging(double value);
    partial void OnquantityChanged();
    partial void Oncutback_rateChanging(System.Nullable<double> value);
    partial void Oncutback_rateChanged();
    partial void OnpriceChanging(double value);
    partial void OnpriceChanged();
    partial void Ondate_timeChanging(System.DateTime value);
    partial void Ondate_timeChanged();
    #endregion
		
		public tbl_return()
		{
			this._tbl_product = default(EntityRef<tbl_product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_return_sn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int return_sn
		{
			get
			{
				return this._return_sn;
			}
			set
			{
				if ((this._return_sn != value))
				{
					this.Onreturn_snChanging(value);
					this.SendPropertyChanging();
					this._return_sn = value;
					this.SendPropertyChanged("return_sn");
					this.Onreturn_snChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sn", DbType="Int NOT NULL")]
		public int product_sn
		{
			get
			{
				return this._product_sn;
			}
			set
			{
				if ((this._product_sn != value))
				{
					if (this._tbl_product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_snChanging(value);
					this.SendPropertyChanging();
					this._product_sn = value;
					this.SendPropertyChanged("product_sn");
					this.Onproduct_snChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Float NOT NULL")]
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cutback_rate", DbType="Float")]
		public System.Nullable<double> cutback_rate
		{
			get
			{
				return this._cutback_rate;
			}
			set
			{
				if ((this._cutback_rate != value))
				{
					this.Oncutback_rateChanging(value);
					this.SendPropertyChanging();
					this._cutback_rate = value;
					this.SendPropertyChanged("cutback_rate");
					this.Oncutback_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime NOT NULL")]
		public System.DateTime date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this.Ondate_timeChanging(value);
					this.SendPropertyChanging();
					this._date_time = value;
					this.SendPropertyChanged("date_time");
					this.Ondate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_product_tbl_return", Storage="_tbl_product", ThisKey="product_sn", OtherKey="product_sn", IsForeignKey=true)]
		public tbl_product tbl_product
		{
			get
			{
				return this._tbl_product.Entity;
			}
			set
			{
				tbl_product previousValue = this._tbl_product.Entity;
				if (((previousValue != value) 
							|| (this._tbl_product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_product.Entity = null;
						previousValue.tbl_returns.Remove(this);
					}
					this._tbl_product.Entity = value;
					if ((value != null))
					{
						value.tbl_returns.Add(this);
						this._product_sn = value.product_sn;
					}
					else
					{
						this._product_sn = default(int);
					}
					this.SendPropertyChanged("tbl_product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sell")]
	public partial class tbl_sell : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sell_id;
		
		private int _product_sn;
		
		private double _quantity;
		
		private double _price;
		
		private string _payment_mode;
		
		private double _due_amount;
		
		private double _paid_amount;
		
		private System.DateTime _date;
		
		private string _customer_name;
		
		private int _contact_no;
		
		private EntityRef<tbl_product> _tbl_product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsell_idChanging(int value);
    partial void Onsell_idChanged();
    partial void Onproduct_snChanging(int value);
    partial void Onproduct_snChanged();
    partial void OnquantityChanging(double value);
    partial void OnquantityChanged();
    partial void OnpriceChanging(double value);
    partial void OnpriceChanged();
    partial void Onpayment_modeChanging(string value);
    partial void Onpayment_modeChanged();
    partial void Ondue_amountChanging(double value);
    partial void Ondue_amountChanged();
    partial void Onpaid_amountChanging(double value);
    partial void Onpaid_amountChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void Oncustomer_nameChanging(string value);
    partial void Oncustomer_nameChanged();
    partial void Oncontact_noChanging(int value);
    partial void Oncontact_noChanged();
    #endregion
		
		public tbl_sell()
		{
			this._tbl_product = default(EntityRef<tbl_product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sell_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sell_id
		{
			get
			{
				return this._sell_id;
			}
			set
			{
				if ((this._sell_id != value))
				{
					this.Onsell_idChanging(value);
					this.SendPropertyChanging();
					this._sell_id = value;
					this.SendPropertyChanged("sell_id");
					this.Onsell_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sn", DbType="Int NOT NULL")]
		public int product_sn
		{
			get
			{
				return this._product_sn;
			}
			set
			{
				if ((this._product_sn != value))
				{
					if (this._tbl_product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_snChanging(value);
					this.SendPropertyChanging();
					this._product_sn = value;
					this.SendPropertyChanged("product_sn");
					this.Onproduct_snChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Float NOT NULL")]
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_mode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string payment_mode
		{
			get
			{
				return this._payment_mode;
			}
			set
			{
				if ((this._payment_mode != value))
				{
					this.Onpayment_modeChanging(value);
					this.SendPropertyChanging();
					this._payment_mode = value;
					this.SendPropertyChanged("payment_mode");
					this.Onpayment_modeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_due_amount", DbType="Float NOT NULL")]
		public double due_amount
		{
			get
			{
				return this._due_amount;
			}
			set
			{
				if ((this._due_amount != value))
				{
					this.Ondue_amountChanging(value);
					this.SendPropertyChanging();
					this._due_amount = value;
					this.SendPropertyChanged("due_amount");
					this.Ondue_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid_amount", DbType="Float NOT NULL")]
		public double paid_amount
		{
			get
			{
				return this._paid_amount;
			}
			set
			{
				if ((this._paid_amount != value))
				{
					this.Onpaid_amountChanging(value);
					this.SendPropertyChanging();
					this._paid_amount = value;
					this.SendPropertyChanged("paid_amount");
					this.Onpaid_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string customer_name
		{
			get
			{
				return this._customer_name;
			}
			set
			{
				if ((this._customer_name != value))
				{
					this.Oncustomer_nameChanging(value);
					this.SendPropertyChanging();
					this._customer_name = value;
					this.SendPropertyChanged("customer_name");
					this.Oncustomer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="Int NOT NULL")]
		public int contact_no
		{
			get
			{
				return this._contact_no;
			}
			set
			{
				if ((this._contact_no != value))
				{
					this.Oncontact_noChanging(value);
					this.SendPropertyChanging();
					this._contact_no = value;
					this.SendPropertyChanged("contact_no");
					this.Oncontact_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_product_tbl_sell", Storage="_tbl_product", ThisKey="product_sn", OtherKey="product_sn", IsForeignKey=true)]
		public tbl_product tbl_product
		{
			get
			{
				return this._tbl_product.Entity;
			}
			set
			{
				tbl_product previousValue = this._tbl_product.Entity;
				if (((previousValue != value) 
							|| (this._tbl_product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_product.Entity = null;
						previousValue.tbl_sells.Remove(this);
					}
					this._tbl_product.Entity = value;
					if ((value != null))
					{
						value.tbl_sells.Add(this);
						this._product_sn = value.product_sn;
					}
					else
					{
						this._product_sn = default(int);
					}
					this.SendPropertyChanged("tbl_product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_staffinfo")]
	public partial class tbl_staffinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sid;
		
		private string _name;
		
		private int _age;
		
		private string _gender;
		
		private string _address;
		
		private System.DateTime _joindate;
		
		private string _qualification;
		
		private double _salary;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsidChanging(int value);
    partial void OnsidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnageChanging(int value);
    partial void OnageChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnjoindateChanging(System.DateTime value);
    partial void OnjoindateChanged();
    partial void OnqualificationChanging(string value);
    partial void OnqualificationChanged();
    partial void OnsalaryChanging(double value);
    partial void OnsalaryChanged();
    #endregion
		
		public tbl_staffinfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sid
		{
			get
			{
				return this._sid;
			}
			set
			{
				if ((this._sid != value))
				{
					this.OnsidChanging(value);
					this.SendPropertyChanging();
					this._sid = value;
					this.SendPropertyChanged("sid");
					this.OnsidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int NOT NULL")]
		public int age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_joindate", DbType="DateTime NOT NULL")]
		public System.DateTime joindate
		{
			get
			{
				return this._joindate;
			}
			set
			{
				if ((this._joindate != value))
				{
					this.OnjoindateChanging(value);
					this.SendPropertyChanging();
					this._joindate = value;
					this.SendPropertyChanged("joindate");
					this.OnjoindateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qualification", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string qualification
		{
			get
			{
				return this._qualification;
			}
			set
			{
				if ((this._qualification != value))
				{
					this.OnqualificationChanging(value);
					this.SendPropertyChanging();
					this._qualification = value;
					this.SendPropertyChanged("qualification");
					this.OnqualificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="Float NOT NULL")]
		public double salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this.OnsalaryChanging(value);
					this.SendPropertyChanging();
					this._salary = value;
					this.SendPropertyChanged("salary");
					this.OnsalaryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_withdrawl")]
	public partial class tbl_withdrawl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _withdraw_id;
		
		private string _withdrawer_name;
		
		private string _description;
		
		private double _amount;
		
		private string _withdraw_type;
		
		private System.DateTime _date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onwithdraw_idChanging(int value);
    partial void Onwithdraw_idChanged();
    partial void Onwithdrawer_nameChanging(string value);
    partial void Onwithdrawer_nameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnamountChanging(double value);
    partial void OnamountChanged();
    partial void Onwithdraw_typeChanging(string value);
    partial void Onwithdraw_typeChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    #endregion
		
		public tbl_withdrawl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_withdraw_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int withdraw_id
		{
			get
			{
				return this._withdraw_id;
			}
			set
			{
				if ((this._withdraw_id != value))
				{
					this.Onwithdraw_idChanging(value);
					this.SendPropertyChanging();
					this._withdraw_id = value;
					this.SendPropertyChanged("withdraw_id");
					this.Onwithdraw_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_withdrawer_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string withdrawer_name
		{
			get
			{
				return this._withdrawer_name;
			}
			set
			{
				if ((this._withdrawer_name != value))
				{
					this.Onwithdrawer_nameChanging(value);
					this.SendPropertyChanging();
					this._withdrawer_name = value;
					this.SendPropertyChanged("withdrawer_name");
					this.Onwithdrawer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Float NOT NULL")]
		public double amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_withdraw_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string withdraw_type
		{
			get
			{
				return this._withdraw_type;
			}
			set
			{
				if ((this._withdraw_type != value))
				{
					this.Onwithdraw_typeChanging(value);
					this.SendPropertyChanging();
					this._withdraw_type = value;
					this.SendPropertyChanged("withdraw_type");
					this.Onwithdraw_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_order_product")]
	public partial class View_order_product
	{
		
		private int _Expr1;
		
		private int _Expr2;
		
		private int _product_sn;
		
		private string _product_name;
		
		private int _unq_orderid;
		
		private string _order_type;
		
		private double _quantity;
		
		private double _bonus_product;
		
		private string _payment_type;
		
		private double _price;
		
		private double _paid_amount;
		
		private double _due_amount;
		
		private string _ordered_to;
		
		private int _contact_no;
		
		private string _order_status;
		
		private System.DateTime _date_time;
		
		public View_order_product()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="Int NOT NULL")]
		public int Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr2", DbType="Int NOT NULL")]
		public int Expr2
		{
			get
			{
				return this._Expr2;
			}
			set
			{
				if ((this._Expr2 != value))
				{
					this._Expr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sn", DbType="Int NOT NULL")]
		public int product_sn
		{
			get
			{
				return this._product_sn;
			}
			set
			{
				if ((this._product_sn != value))
				{
					this._product_sn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this._product_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unq_orderid", DbType="Int NOT NULL")]
		public int unq_orderid
		{
			get
			{
				return this._unq_orderid;
			}
			set
			{
				if ((this._unq_orderid != value))
				{
					this._unq_orderid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string order_type
		{
			get
			{
				return this._order_type;
			}
			set
			{
				if ((this._order_type != value))
				{
					this._order_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Float NOT NULL")]
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this._quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bonus_product", DbType="Float NOT NULL")]
		public double bonus_product
		{
			get
			{
				return this._bonus_product;
			}
			set
			{
				if ((this._bonus_product != value))
				{
					this._bonus_product = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string payment_type
		{
			get
			{
				return this._payment_type;
			}
			set
			{
				if ((this._payment_type != value))
				{
					this._payment_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid_amount", DbType="Float NOT NULL")]
		public double paid_amount
		{
			get
			{
				return this._paid_amount;
			}
			set
			{
				if ((this._paid_amount != value))
				{
					this._paid_amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_due_amount", DbType="Float NOT NULL")]
		public double due_amount
		{
			get
			{
				return this._due_amount;
			}
			set
			{
				if ((this._due_amount != value))
				{
					this._due_amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordered_to", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ordered_to
		{
			get
			{
				return this._ordered_to;
			}
			set
			{
				if ((this._ordered_to != value))
				{
					this._ordered_to = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="Int NOT NULL")]
		public int contact_no
		{
			get
			{
				return this._contact_no;
			}
			set
			{
				if ((this._contact_no != value))
				{
					this._contact_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string order_status
		{
			get
			{
				return this._order_status;
			}
			set
			{
				if ((this._order_status != value))
				{
					this._order_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_time", DbType="DateTime NOT NULL")]
		public System.DateTime date_time
		{
			get
			{
				return this._date_time;
			}
			set
			{
				if ((this._date_time != value))
				{
					this._date_time = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_sell")]
	public partial class view_sell
	{
		
		private int _sell_id;
		
		private int _product_sn;
		
		private double _quantity;
		
		private double _price;
		
		private string _payment_mode;
		
		private double _due_amount;
		
		private double _paid_amount;
		
		private System.DateTime _date;
		
		private string _customer_name;
		
		private int _contact_no;
		
		private int _Expr1;
		
		private string _product_name;
		
		private string _product_group;
		
		private double _quantity_per_box;
		
		private string _company_name;
		
		private double _price_per_box;
		
		private double _comission_rate_percentege;
		
		public view_sell()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sell_id", DbType="Int NOT NULL")]
		public int sell_id
		{
			get
			{
				return this._sell_id;
			}
			set
			{
				if ((this._sell_id != value))
				{
					this._sell_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sn", DbType="Int NOT NULL")]
		public int product_sn
		{
			get
			{
				return this._product_sn;
			}
			set
			{
				if ((this._product_sn != value))
				{
					this._product_sn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Float NOT NULL")]
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this._quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_mode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string payment_mode
		{
			get
			{
				return this._payment_mode;
			}
			set
			{
				if ((this._payment_mode != value))
				{
					this._payment_mode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_due_amount", DbType="Float NOT NULL")]
		public double due_amount
		{
			get
			{
				return this._due_amount;
			}
			set
			{
				if ((this._due_amount != value))
				{
					this._due_amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid_amount", DbType="Float NOT NULL")]
		public double paid_amount
		{
			get
			{
				return this._paid_amount;
			}
			set
			{
				if ((this._paid_amount != value))
				{
					this._paid_amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string customer_name
		{
			get
			{
				return this._customer_name;
			}
			set
			{
				if ((this._customer_name != value))
				{
					this._customer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="Int NOT NULL")]
		public int contact_no
		{
			get
			{
				return this._contact_no;
			}
			set
			{
				if ((this._contact_no != value))
				{
					this._contact_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="Int NOT NULL")]
		public int Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this._product_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_group", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string product_group
		{
			get
			{
				return this._product_group;
			}
			set
			{
				if ((this._product_group != value))
				{
					this._product_group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity_per_box", DbType="Float NOT NULL")]
		public double quantity_per_box
		{
			get
			{
				return this._quantity_per_box;
			}
			set
			{
				if ((this._quantity_per_box != value))
				{
					this._quantity_per_box = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string company_name
		{
			get
			{
				return this._company_name;
			}
			set
			{
				if ((this._company_name != value))
				{
					this._company_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_per_box", DbType="Float NOT NULL")]
		public double price_per_box
		{
			get
			{
				return this._price_per_box;
			}
			set
			{
				if ((this._price_per_box != value))
				{
					this._price_per_box = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comission_rate_percentege", DbType="Float NOT NULL")]
		public double comission_rate_percentege
		{
			get
			{
				return this._comission_rate_percentege;
			}
			set
			{
				if ((this._comission_rate_percentege != value))
				{
					this._comission_rate_percentege = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
