//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmecyMgt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Paul-PC\\sqlexpress;Initial Catalog=\"Pharmecy Mgt.\";Integrated Securit" +
            "y=True")]
        public string Pharmecy_Mgt_ConnectionString {
            get {
                return ((string)(this["Pharmecy_Mgt_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=anu-pc\\sqlexpress;AttachDbFilename=\"C:\\Program Files\\Microsoft SQL Se" +
            "rver\\MSSQL.1\\MSSQL\\Data\\Pharmecy Mgt..mdf\";Integrated Security=True")]
        public string Pharmecy_Mgt_ConnectionString1 {
            get {
                return ((string)(this["Pharmecy_Mgt_ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=anu-pc\\sqlexpress;Initial Catalog=\"Pharmecy Mgt.\";Integrated Security" +
            "=True")]
        public string Pharmecy_Mgt_ConnectionString2 {
            get {
                return ((string)(this["Pharmecy_Mgt_ConnectionString2"]));
            }
        }
        
        
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PAUL-PC\\SQLEXPRESS;Initial Catalog=\"Pharmecy Mgt.\";Integrated Securit" +
            "y=True")]
        public string Pharmecy_Mgt_ConnectionString3 {
            get {
                return ((string)(this["Pharmecy_Mgt_ConnectionString3"]));
            }
        }
    }
}
